version: "3.7"

services:

  tests:
    build:
      context:  .
      dockerfile: ./Dockerfile.tests
    command: ["pytest", "-vv", "-ra", "-s", "--disable-warnings"]
    environment:
      SECRET: secret
    volumes:
        - ./:/app